language: node_js
node_js:
  - 0.10
  - 5.8.0
  - 8
  - 9
  - 11
before_install:
  - npm install -g qnit
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc codecov coveralls
  - nyc -r text --reporter lcov npm test && codecov
  - nyc report -r text-lcov | coveralls
